import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import Image from "next/image";
import HomeIcon from "@/components/icons/HomeIcon";
import MsgIcon from "@/components/icons/MsgIcon";
import ProfileIcon from "@/components/icons/ProfileIcon";
import SettingsIcon from "@/components/icons/SettingsIcon";
import AddingIcon from "@/components/icons/AddingIcon";
import AlertIcon from "@/components/icons/AlertIcon";


const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "TalkUp Mental Health Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <section className="flex flex-row">
          <div className="bg-[#F6FAFF] w-[350px] h-screen flex flex-col fixed overflow-auto z-10">
            <div className="flex p-8 pt-[70px]">
              <Image src="/logo.webp" alt="logo" width={40} height={40} />
              <h5 className="font-extrabold text-[25px] ml-2">TalkUp.</h5>
            </div>
            <div className="flex flex-col p-8 space-y-4 flex-grow">
              <div className="flex bg-[#DFEFFF] w-full p-3 rounded-xl text-[#0D90FF]">
                <HomeIcon size={12} color={"#0D90FF"} />
                <p className="text-[20px] ml-3">Dashboard</p>
              </div>
              <div className="flex w-full p-3 rounded-xl text-[#85878A]">
                <MsgIcon size={12} color={"#85878A"} />
                <p className="text-[20px] ml-3">Message</p>
              </div>
              <div className="flex w-full p-3 rounded-xl text-[#85878A]">
                <ProfileIcon size={12} color={"#85878A"} />
                <p className="text-[20px] ml-3">Profile</p>
              </div>
              <div className="flex w-full p-3 rounded-xl text-[#85878A]">
                <SettingsIcon size={12} color={"#85878A"} />
                <p className="text-[20px] ml-3">Setting</p>
              </div>
              <div className="flex w-full p-3 rounded-xl text-[#85878A]">
                <AddingIcon size={12} color={"#85878A"} />
                <p className="text-[20px] ml-3">Add Story</p>
              </div>
            </div>
            <div className="p-8">
              <div className="flex bg-[#DFEFFF] w-full p-3 rounded-xl text-[#0D90FF]">
                <AlertIcon size={12} color={"#0D90FF"} />
                <p className="text-[17px] ml-3">Term and Services</p>
              </div>
            </div>
          </div>
          <div className="pl-[350px] overflow-auto">{children}</div>
        </section>
      </body>
    </html>
  );
}
