export const forbiddenWords = [
    "Fking",
    "Fck",
    "Fk",
    "Fucking",
    "Cumbubble",
    "Fuck",
    "Fuck you",
    "Shitbag",
    "Shit",
    "Piss off",
    "Asshole",
    "Dickweed",
    "Cunt",
    "Son of a bitch",
    "Fuck trumpet",
    "Bastard",
    "Bitch",
    "Damn",
    "Bollocks",
    "Bugger",
    "Cocknose",
    "Bloody hell",
    "Knobhead",
    "Choad",
    "Bitchtits",
    "Crikey",
    "Rubbish",
    "Pissflaps",
    "Shag",
    "Wanker",
    "Talking the piss",
    "Twat",
    "Arsebadger",
    "Jizzcock",
    "Cumdumpster",
    "Shitmagnet",
    "Scrote",
    "Twatwaffle",
    "Thundercunt",
    "Dickhead",
    "Shitpouch",
    "Jizzstain",
    "Nonce",
    "Pisskidney",
    "Wazzock",
    "Cumwipe",
    "Fanny",
    "Bellend",
    "Pisswizard",
    "Knobjockey",
    "Cuntpuddle",
    "Dickweasel",
    "Quim",
    "Bawbag",
    "Fuckwit",
    "Tosspot",
    "Cockwomble",
    "Twat face",
    "Cack",
    "Flange",
    "Clunge",
    "Dickfucker",
    "Fannyflaps",
    "Wankface",
    "Shithouse",
    "Gobshite",
    "Jizzbreath",
    "Todger",
    "Nutsack",
    "Cumb*bble",
    "F*ck",
    "F*ck you",
    "Shitb*g",
    "Sh*t",
    "P*ss off",
    "Assh*le",
    "D*ckweed",
    "C*nt",
    "Son of a b*tch",
    "F*ck trumpet",
    "B*stard",
    "B*tch",
    "Damn",
    "Bllcks",
    "B*gger",
    "C*cknose",
    "Bl**dy hell",
    "Kn*bhead",
    "Ch**d",
    "Btchtts",
    "Cr*key",
    "R*bbish",
    "Pssflps",
    "Sh*g",
    "W*nker",
    "Talking the p*ss",
    "Tw*t",
    "Arseb*dger",
    "J*zzcock",
    "C*mdumpster",
    "Sh*tmagnet",
    "Scr*te",
    "Tw*twaffle",
    "Thndercnt",
    "D*ckhead",
    "Sh*tpouch",
    "J*zzstain",
    "N*nce",
    "Psskdney",
    "W*zzock",
    "C*mwipe",
    "F*nny",
    "Bell*nd",
    "P*sswizard",
    "Kn*bjockey",
    "C*ntpuddle",
    "D*ckweasel",
    "Qu*m",
    "B*wbag",
    "F*ckwit",
    "T*sspot",
    "C*ckwomble",
    "Tw*t face",
    "C*ck",
    "Fl*nge",
    "Cl*nge",
    "Dckfcker",
    "Fnnyflps",
    "W*nkface",
    "Sh*thouse",
    "G*bshite",
    "J*zzbreath",
    "T*dger",
    "N*tsack"
  ];